In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
features = [
    # Financial (core)
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",

    # Employment
    "NAME_INCOME_TYPE",
    "OCCUPATION_TYPE",
    "DAYS_EMPLOYED",

    # Demographics
    "DAYS_BIRTH",
    "CODE_GENDER",
    "NAME_FAMILY_STATUS",
    "CNT_CHILDREN",
    "CNT_FAM_MEMBERS",

    # Assets
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",

    # Behavior

    "DAYS_LAST_PHONE_CHANGE",
    
    "TARGET"
    
]

In [3]:
df = pd.read_csv(r"C:\Main_Drive\work\workarea\projects\credit_risk_prediction\data\home-credit-default-risk\application_train.csv",usecols=features)

In [4]:
df

,TARGET,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,DAYS_BIRTH,DAYS_EMPLOYED,OCCUPATION_TYPE,CNT_FAM_MEMBERS,DAYS_LAST_PHONE_CHANGE
0,1,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,Single / not married,-9461,-637,Laborers,1.0,-1134.0
1,0,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,Married,-16765,-1188,Core staff,2.0,-828.0
2,0,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,Single / not married,-19046,-225,Laborers,1.0,-815.0
3,0,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,Civil marriage,-19005,-3039,Laborers,2.0,-617.0
4,0,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,Single / not married,-19932,-3038,Core staff,1.0,-1106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,0,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Working,Separated,-9327,-236,Sales staff,1.0,-273.0
307507,0,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Pensioner,Widow,-20775,365243,NaN,1.0,0.0
307508,0,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Working,Separated,-14966,-7921,Managers,1.0,-1909.0
307509,1,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Commercial associate,Married,-11961,-4786,Laborers,2.0,-322.0
307510,0,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Commercial associate,Married,-16856,-1262,Laborers,2.0,-787.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   TARGET                  307511 non-null  int64
 1   CODE_GENDER             307511 non-null  object
 2   FLAG_OWN_CAR            307511 non-null  object
 3   FLAG_OWN_REALTY         307511 non-null  object
 4   CNT_CHILDREN            307511 non-null  int64
 5   AMT_INCOME_TOTAL        307511 non-null  float64
 6   AMT_CREDIT              307511 non-null  float64
 7   AMT_ANNUITY             307499 non-null  float64
 8   AMT_GOODS_PRICE         307233 non-null  float64
 9   NAME_INCOME_TYPE        307511 non-null  object
 10  NAME_FAMILY_STATUS      307511 non-null  object
 11  DAYS_BIRTH              307511 non-null  int64
 12  DAYS_EMPLOYED           307511 non-null  int64
 13  OCCUPATION_TYPE         211120 non-null  object
 14  CNT_FAM_MEMBERS         307509 non-null  float64
 15  DAYS_LAST_PHONE_CHANGE  307510 non-null  float64
dtypes: float64(6), int64(4), object(6)
memory usage: 37.5+ MB

In [6]:
df.describe()

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,DAYS_BIRTH,DAYS_EMPLOYED,CNT_FAM_MEMBERS,DAYS_LAST_PHONE_CHANGE
count,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307509.000000,307510.000000
mean,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,-16036.995067,63815.045904,2.152665,-962.858788
std,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,4363.988632,141275.766519,0.910682,826.808487
min,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,-25229.000000,-17912.000000,1.000000,-4292.000000
25%,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,-19682.000000,-2760.000000,2.000000,-1570.000000
50%,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,-15750.000000,-1213.000000,2.000000,-757.000000
75%,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,-12413.000000,-289.000000,3.000000,-274.000000
max,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,-7489.000000,365243.000000,20.000000,0.000000

In [7]:
df.select_dtypes(object)

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE
0,M,N,Y,Working,Single / not married,Laborers
1,F,N,N,State servant,Married,Core staff
2,M,Y,Y,Working,Single / not married,Laborers
3,F,N,Y,Working,Civil marriage,Laborers
4,M,N,Y,Working,Single / not married,Core staff
...,...,...,...,...,...,...
307506,M,N,N,Working,Separated,Sales staff
307507,F,N,Y,Pensioner,Widow,NaN
307508,F,N,Y,Working,Separated,Managers
307509,F,N,Y,Commercial associate,Married,Laborers
307510,F,N,N,Commercial associate,Married,Laborers

In [8]:
df.columns = df.columns.str.title()
df

,Target,Code_Gender,Flag_Own_Car,Flag_Own_Realty,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Name_Income_Type,Name_Family_Status,Days_Birth,Days_Employed,Occupation_Type,Cnt_Fam_Members,Days_Last_Phone_Change
0,1,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,Single / not married,-9461,-637,Laborers,1.0,-1134.0
1,0,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,Married,-16765,-1188,Core staff,2.0,-828.0
2,0,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,Single / not married,-19046,-225,Laborers,1.0,-815.0
3,0,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,Civil marriage,-19005,-3039,Laborers,2.0,-617.0
4,0,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,Single / not married,-19932,-3038,Core staff,1.0,-1106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,0,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Working,Separated,-9327,-236,Sales staff,1.0,-273.0
307507,0,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Pensioner,Widow,-20775,365243,NaN,1.0,0.0
307508,0,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Working,Separated,-14966,-7921,Managers,1.0,-1909.0
307509,1,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Commercial associate,Married,-11961,-4786,Laborers,2.0,-322.0
307510,0,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Commercial associate,Married,-16856,-1262,Laborers,2.0,-787.0

In [9]:
df.isnull().sum()

Target                        0
Code_Gender                   0
Flag_Own_Car                  0
Flag_Own_Realty               0
Cnt_Children                  0
Amt_Income_Total              0
Amt_Credit                    0
Amt_Annuity                  12
Amt_Goods_Price             278
Name_Income_Type              0
Name_Family_Status            0
Days_Birth                    0
Days_Employed                 0
Occupation_Type           96391
Cnt_Fam_Members               2
Days_Last_Phone_Change        1
dtype: int64

In [10]:
df.isnull().sum()

Target                        0
Code_Gender                   0
Flag_Own_Car                  0
Flag_Own_Realty               0
Cnt_Children                  0
Amt_Income_Total              0
Amt_Credit                    0
Amt_Annuity                  12
Amt_Goods_Price             278
Name_Income_Type              0
Name_Family_Status            0
Days_Birth                    0
Days_Employed                 0
Occupation_Type           96391
Cnt_Fam_Members               2
Days_Last_Phone_Change        1
dtype: int64

In [11]:
df["Cnt_Fam_Members"] = df["Cnt_Fam_Members"].fillna(df["Cnt_Fam_Members"].median())

In [12]:
df.isnull().sum()

Target                        0
Code_Gender                   0
Flag_Own_Car                  0
Flag_Own_Realty               0
Cnt_Children                  0
Amt_Income_Total              0
Amt_Credit                    0
Amt_Annuity                  12
Amt_Goods_Price             278
Name_Income_Type              0
Name_Family_Status            0
Days_Birth                    0
Days_Employed                 0
Occupation_Type           96391
Cnt_Fam_Members               0
Days_Last_Phone_Change        1
dtype: int64

In [13]:
df["Days_Last_Phone_Change"] = df["Days_Last_Phone_Change"].fillna(df["Days_Last_Phone_Change"].mean())

In [14]:
df.isnull().sum()

Target                        0
Code_Gender                   0
Flag_Own_Car                  0
Flag_Own_Realty               0
Cnt_Children                  0
Amt_Income_Total              0
Amt_Credit                    0
Amt_Annuity                  12
Amt_Goods_Price             278
Name_Income_Type              0
Name_Family_Status            0
Days_Birth                    0
Days_Employed                 0
Occupation_Type           96391
Cnt_Fam_Members               0
Days_Last_Phone_Change        0
dtype: int64

In [15]:
df

,Target,Code_Gender,Flag_Own_Car,Flag_Own_Realty,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Name_Income_Type,Name_Family_Status,Days_Birth,Days_Employed,Occupation_Type,Cnt_Fam_Members,Days_Last_Phone_Change
0,1,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,Single / not married,-9461,-637,Laborers,1.0,-1134.0
1,0,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,Married,-16765,-1188,Core staff,2.0,-828.0
2,0,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,Single / not married,-19046,-225,Laborers,1.0,-815.0
3,0,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,Civil marriage,-19005,-3039,Laborers,2.0,-617.0
4,0,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,Single / not married,-19932,-3038,Core staff,1.0,-1106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,0,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Working,Separated,-9327,-236,Sales staff,1.0,-273.0
307507,0,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Pensioner,Widow,-20775,365243,NaN,1.0,0.0
307508,0,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Working,Separated,-14966,-7921,Managers,1.0,-1909.0
307509,1,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Commercial associate,Married,-11961,-4786,Laborers,2.0,-322.0
307510,0,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Commercial associate,Married,-16856,-1262,Laborers,2.0,-787.0

In [16]:
df["Occupation_Type"] = df["Occupation_Type"].fillna(df["Occupation_Type"].mode()[0])

In [17]:
df.isnull().sum()

Target                      0
Code_Gender                 0
Flag_Own_Car                0
Flag_Own_Realty             0
Cnt_Children                0
Amt_Income_Total            0
Amt_Credit                  0
Amt_Annuity                12
Amt_Goods_Price           278
Name_Income_Type            0
Name_Family_Status          0
Days_Birth                  0
Days_Employed               0
Occupation_Type             0
Cnt_Fam_Members             0
Days_Last_Phone_Change      0
dtype: int64

In [18]:
df["Amt_Annuity"] = df["Amt_Annuity"].fillna(df["Amt_Annuity"].mean())
df["Amt_Goods_Price"] = df["Amt_Goods_Price"].fillna(df["Amt_Goods_Price"].mean())
df.isnull().sum()

Target                    0
Code_Gender               0
Flag_Own_Car              0
Flag_Own_Realty           0
Cnt_Children              0
Amt_Income_Total          0
Amt_Credit                0
Amt_Annuity               0
Amt_Goods_Price           0
Name_Income_Type          0
Name_Family_Status        0
Days_Birth                0
Days_Employed             0
Occupation_Type           0
Cnt_Fam_Members           0
Days_Last_Phone_Change    0
dtype: int64

In [19]:
categorical_feature_df = df.select_dtypes(include=object)

In [20]:
categorical_feature=categorical_feature_df.columns.tolist()

In [21]:
categorical_feature

['Code_Gender',
 'Flag_Own_Car',
 'Flag_Own_Realty',
 'Name_Income_Type',
 'Name_Family_Status',
 'Occupation_Type']

In [22]:
numerical_feature_df = df.select_dtypes(exclude=object).drop(columns = ["Target"])

In [23]:
numerical_feature = numerical_feature_df.columns.tolist()

In [24]:
numerical_feature

['Cnt_Children',
 'Amt_Income_Total',
 'Amt_Credit',
 'Amt_Annuity',
 'Amt_Goods_Price',
 'Days_Birth',
 'Days_Employed',
 'Cnt_Fam_Members',
 'Days_Last_Phone_Change']

In [25]:
#encoding
categorical_feature_df.nunique()

Code_Gender            3
Flag_Own_Car           2
Flag_Own_Realty        2
Name_Income_Type       8
Name_Family_Status     6
Occupation_Type       18
dtype: int64

In [26]:
categorical_feature_df

,Code_Gender,Flag_Own_Car,Flag_Own_Realty,Name_Income_Type,Name_Family_Status,Occupation_Type
0,M,N,Y,Working,Single / not married,Laborers
1,F,N,N,State servant,Married,Core staff
2,M,Y,Y,Working,Single / not married,Laborers
3,F,N,Y,Working,Civil marriage,Laborers
4,M,N,Y,Working,Single / not married,Core staff
...,...,...,...,...,...,...
307506,M,N,N,Working,Separated,Sales staff
307507,F,N,Y,Pensioner,Widow,Laborers
307508,F,N,Y,Working,Separated,Managers
307509,F,N,Y,Commercial associate,Married,Laborers
307510,F,N,N,Commercial associate,Married,Laborers

In [27]:
categorical_feature_df["Code_Gender"].unique()

array(['M', 'F', 'XNA'], dtype=object)

In [28]:
categorical_feature_df["Flag_Own_Car"].unique()

array(['N', 'Y'], dtype=object)

In [29]:
categorical_feature_df["Flag_Own_Realty"].unique()

array(['Y', 'N'], dtype=object)

In [30]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder

In [31]:
# LabelEncoder

le = LabelEncoder()
df["Flag_Own_Car2"] = le.fit_transform(df["Flag_Own_Car"])
df["Flag_Own_Realty2"] = le.fit_transform(df["Flag_Own_Realty"])

df = df.drop(columns = ["Flag_Own_Realty2","Flag_Own_Car2"])

In [32]:
# Label Encoding 
mapping = {"Y":1,"N":0}
df["Flag_Own_Car2"]=df["Flag_Own_Car"].map(mapping)
df["Flag_Own_Realty2"]=df["Flag_Own_Realty"].map(mapping)

In [33]:
df

,Target,Code_Gender,Flag_Own_Car,Flag_Own_Realty,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Name_Income_Type,Name_Family_Status,Days_Birth,Days_Employed,Occupation_Type,Cnt_Fam_Members,Days_Last_Phone_Change,Flag_Own_Car2,Flag_Own_Realty2
0,1,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,Single / not married,-9461,-637,Laborers,1.0,-1134.0,0,1
1,0,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,Married,-16765,-1188,Core staff,2.0,-828.0,0,0
2,0,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,Single / not married,-19046,-225,Laborers,1.0,-815.0,1,1
3,0,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,Civil marriage,-19005,-3039,Laborers,2.0,-617.0,0,1
4,0,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,Single / not married,-19932,-3038,Core staff,1.0,-1106.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,0,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Working,Separated,-9327,-236,Sales staff,1.0,-273.0,0,0
307507,0,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Pensioner,Widow,-20775,365243,Laborers,1.0,0.0,0,1
307508,0,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Working,Separated,-14966,-7921,Managers,1.0,-1909.0,0,1
307509,1,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Commercial associate,Married,-11961,-4786,Laborers,2.0,-322.0,0,1
307510,0,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Commercial associate,Married,-16856,-1262,Laborers,2.0,-787.0,0,0

In [34]:
# One Hot Encoder
OHE = OneHotEncoder(sparse_output=False)
OHE

OneHotEncoder(sparse_output=False)

In [35]:
gender_array = OHE.fit_transform(df[["Code_Gender"]])
gender_array

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], shape=(307511, 3))

In [36]:
gender_df = pd.DataFrame(gender_array,
                         columns = OHE.get_feature_names_out(["Code_Gender"]),
                        index = df.index)

In [37]:
gender_df

        Code_Gender_F  Code_Gender_M  Code_Gender_XNA
0                 0.0            1.0              0.0
1                 1.0            0.0              0.0
2                 0.0            1.0              0.0
3                 1.0            0.0              0.0
4                 0.0            1.0              0.0
...               ...            ...              ...
307506            0.0            1.0              0.0
307507            1.0            0.0              0.0
307508            1.0            0.0              0.0
307509            1.0            0.0              0.0
307510            1.0            0.0              0.0

[307511 rows x 3 columns]

In [38]:
df1 = pd.concat([df,gender_df],axis = 1)

In [39]:
df1

,Target,Code_Gender,Flag_Own_Car,Flag_Own_Realty,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Name_Income_Type,...,Days_Birth,Days_Employed,Occupation_Type,Cnt_Fam_Members,Days_Last_Phone_Change,Flag_Own_Car2,Flag_Own_Realty2,Code_Gender_F,Code_Gender_M,Code_Gender_XNA
0,1,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,...,-9461,-637,Laborers,1.0,-1134.0,0,1,0.0,1.0,0.0
1,0,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,...,-16765,-1188,Core staff,2.0,-828.0,0,0,1.0,0.0,0.0
2,0,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,...,-19046,-225,Laborers,1.0,-815.0,1,1,0.0,1.0,0.0
3,0,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,...,-19005,-3039,Laborers,2.0,-617.0,0,1,1.0,0.0,0.0
4,0,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,...,-19932,-3038,Core staff,1.0,-1106.0,0,1,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,0,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Working,...,-9327,-236,Sales staff,1.0,-273.0,0,0,0.0,1.0,0.0
307507,0,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Pensioner,...,-20775,365243,Laborers,1.0,0.0,0,1,1.0,0.0,0.0
307508,0,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Working,...,-14966,-7921,Managers,1.0,-1909.0,0,1,1.0,0.0,0.0
307509,1,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Commercial associate,...,-11961,-4786,Laborers,2.0,-322.0,0,1,1.0,0.0,0.0
307510,0,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Commercial associate,...,-16856,-1262,Laborers,2.0,-787.0,0,0,1.0,0.0,0.0

In [40]:
# OHE using pandas 
OHE_dummy_df = pd.get_dummies(df[["Name_Income_Type","Name_Family_Status","Occupation_Type"]])

OHE_dummy_df=OHE_dummy_df.astype(int)

In [41]:
df1 = pd.concat([df1,OHE_dummy_df],axis = 1)

In [42]:
pd.set_option('display.max_colwidth', None)

In [43]:
df1

,Target,Code_Gender,Flag_Own_Car,Flag_Own_Realty,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Name_Income_Type,...,Occupation_Type_Laborers,Occupation_Type_Low-skill Laborers,Occupation_Type_Managers,Occupation_Type_Medicine staff,Occupation_Type_Private service staff,Occupation_Type_Realty agents,Occupation_Type_Sales staff,Occupation_Type_Secretaries,Occupation_Type_Security staff,Occupation_Type_Waiters/barmen staff
0,1,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,...,1,0,0,0,0,0,0,0,0,0
1,0,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,...,0,0,0,0,0,0,0,0,0,0
2,0,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,...,1,0,0,0,0,0,0,0,0,0
3,0,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,...,1,0,0,0,0,0,0,0,0,0
4,0,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,0,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Working,...,0,0,0,0,0,0,1,0,0,0
307507,0,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Pensioner,...,1,0,0,0,0,0,0,0,0,0
307508,0,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Working,...,0,0,1,0,0,0,0,0,0,0
307509,1,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Commercial associate,...,1,0,0,0,0,0,0,0,0,0
307510,0,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Commercial associate,...,1,0,0,0,0,0,0,0,0,0

In [44]:
df1.columns.tolist()

['Target',
 'Code_Gender',
 'Flag_Own_Car',
 'Flag_Own_Realty',
 'Cnt_Children',
 'Amt_Income_Total',
 'Amt_Credit',
 'Amt_Annuity',
 'Amt_Goods_Price',
 'Name_Income_Type',
 'Name_Family_Status',
 'Days_Birth',
 'Days_Employed',
 'Occupation_Type',
 'Cnt_Fam_Members',
 'Days_Last_Phone_Change',
 'Flag_Own_Car2',
 'Flag_Own_Realty2',
 'Code_Gender_F',
 'Code_Gender_M',
 'Code_Gender_XNA',
 'Name_Income_Type_Businessman',
 'Name_Income_Type_Commercial associate',
 'Name_Income_Type_Maternity leave',
 'Name_Income_Type_Pensioner',
 'Name_Income_Type_State servant',
 'Name_Income_Type_Student',
 'Name_Income_Type_Unemployed',
 'Name_Income_Type_Working',
 'Name_Family_Status_Civil marriage',
 'Name_Family_Status_Married',
 'Name_Family_Status_Separated',
 'Name_Family_Status_Single / not married',
 'Name_Family_Status_Unknown',
 'Name_Family_Status_Widow',
 'Occupation_Type_Accountants',
 'Occupation_Type_Cleaning staff',
 'Occupation_Type_Cooking staff',
 'Occupation_Type_Core staff',
 'Occupation_Type_Drivers',
 'Occupation_Type_HR staff',
 'Occupation_Type_High skill tech staff',
 'Occupation_Type_IT staff',
 'Occupation_Type_Laborers',
 'Occupation_Type_Low-skill Laborers',
 'Occupation_Type_Managers',
 'Occupation_Type_Medicine staff',
 'Occupation_Type_Private service staff',
 'Occupation_Type_Realty agents',
 'Occupation_Type_Sales staff',
 'Occupation_Type_Secretaries',
 'Occupation_Type_Security staff',
 'Occupation_Type_Waiters/barmen staff']

In [45]:
df2=df1.drop(columns = categorical_feature)

In [46]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 47 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   Target                                   307511 non-null  int64
 1   Cnt_Children                             307511 non-null  int64
 2   Amt_Income_Total                         307511 non-null  float64
 3   Amt_Credit                               307511 non-null  float64
 4   Amt_Annuity                              307511 non-null  float64
 5   Amt_Goods_Price                          307511 non-null  float64
 6   Days_Birth                               307511 non-null  int64
 7   Days_Employed                            307511 non-null  int64
 8   Cnt_Fam_Members                          307511 non-null  float64
 9   Days_Last_Phone_Change                   307511 non-null  float64
 10  Flag_Own_Car2                            307511 non-null  int64
 11  Flag_Own_Realty2                         307511 non-null  int64
 12  Code_Gender_F                            307511 non-null  float64
 13  Code_Gender_M                            307511 non-null  float64
 14  Code_Gender_XNA                          307511 non-null  float64
 15  Name_Income_Type_Businessman             307511 non-null  int64
 16  Name_Income_Type_Commercial associate    307511 non-null  int64
 17  Name_Income_Type_Maternity leave         307511 non-null  int64
 18  Name_Income_Type_Pensioner               307511 non-null  int64
 19  Name_Income_Type_State servant           307511 non-null  int64
 20  Name_Income_Type_Student                 307511 non-null  int64
 21  Name_Income_Type_Unemployed              307511 non-null  int64
 22  Name_Income_Type_Working                 307511 non-null  int64
 23  Name_Family_Status_Civil marriage        307511 non-null  int64
 24  Name_Family_Status_Married               307511 non-null  int64
 25  Name_Family_Status_Separated             307511 non-null  int64
 26  Name_Family_Status_Single / not married  307511 non-null  int64
 27  Name_Family_Status_Unknown               307511 non-null  int64
 28  Name_Family_Status_Widow                 307511 non-null  int64
 29  Occupation_Type_Accountants              307511 non-null  int64
 30  Occupation_Type_Cleaning staff           307511 non-null  int64
 31  Occupation_Type_Cooking staff            307511 non-null  int64
 32  Occupation_Type_Core staff               307511 non-null  int64
 33  Occupation_Type_Drivers                  307511 non-null  int64
 34  Occupation_Type_HR staff                 307511 non-null  int64
 35  Occupation_Type_High skill tech staff    307511 non-null  int64
 36  Occupation_Type_IT staff                 307511 non-null  int64
 37  Occupation_Type_Laborers                 307511 non-null  int64
 38  Occupation_Type_Low-skill Laborers       307511 non-null  int64
 39  Occupation_Type_Managers                 307511 non-null  int64
 40  Occupation_Type_Medicine staff           307511 non-null  int64
 41  Occupation_Type_Private service staff    307511 non-null  int64
 42  Occupation_Type_Realty agents            307511 non-null  int64
 43  Occupation_Type_Sales staff              307511 non-null  int64
 44  Occupation_Type_Secretaries              307511 non-null  int64
 45  Occupation_Type_Security staff           307511 non-null  int64
 46  Occupation_Type_Waiters/barmen staff     307511 non-null  int64
dtypes: float64(9), int64(38)
memory usage: 110.3 MB

In [47]:
df2

,Target,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Days_Birth,Days_Employed,Cnt_Fam_Members,Days_Last_Phone_Change,...,Occupation_Type_Laborers,Occupation_Type_Low-skill Laborers,Occupation_Type_Managers,Occupation_Type_Medicine staff,Occupation_Type_Private service staff,Occupation_Type_Realty agents,Occupation_Type_Sales staff,Occupation_Type_Secretaries,Occupation_Type_Security staff,Occupation_Type_Waiters/barmen staff
0,1,0,202500.0,406597.5,24700.5,351000.0,-9461,-637,1.0,-1134.0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,270000.0,1293502.5,35698.5,1129500.0,-16765,-1188,2.0,-828.0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,67500.0,135000.0,6750.0,135000.0,-19046,-225,1.0,-815.0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,135000.0,312682.5,29686.5,297000.0,-19005,-3039,2.0,-617.0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,121500.0,513000.0,21865.5,513000.0,-19932,-3038,1.0,-1106.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,0,0,157500.0,254700.0,27558.0,225000.0,-9327,-236,1.0,-273.0,...,0,0,0,0,0,0,1,0,0,0
307507,0,0,72000.0,269550.0,12001.5,225000.0,-20775,365243,1.0,0.0,...,1,0,0,0,0,0,0,0,0,0
307508,0,0,153000.0,677664.0,29979.0,585000.0,-14966,-7921,1.0,-1909.0,...,0,0,1,0,0,0,0,0,0,0
307509,1,0,171000.0,370107.0,20205.0,319500.0,-11961,-4786,2.0,-322.0,...,1,0,0,0,0,0,0,0,0,0
307510,0,0,157500.0,675000.0,49117.5,675000.0,-16856,-1262,2.0,-787.0,...,1,0,0,0,0,0,0,0,0,0

In [48]:
corr_matrix = df2.corr().sort_values(by=["Target"],ascending=False)
corr_matrix

,Target,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Days_Birth,Days_Employed,Cnt_Fam_Members,Days_Last_Phone_Change,...,Occupation_Type_Laborers,Occupation_Type_Low-skill Laborers,Occupation_Type_Managers,Occupation_Type_Medicine staff,Occupation_Type_Private service staff,Occupation_Type_Realty agents,Occupation_Type_Sales staff,Occupation_Type_Secretaries,Occupation_Type_Security staff,Occupation_Type_Waiters/barmen staff
Target,1.000000,0.019187,-0.003982,-0.030369,-0.012817,-3.962841e-02,0.078239,-0.044932,0.009308,0.055218,...,-0.002880,0.027591,-0.018648,-0.008514,-0.005047,-0.000394,0.019537,-0.002452,0.014648,0.007802
Days_Birth,0.078239,0.330938,0.027261,-0.055436,0.009445,-5.341634e-02,1.000000,-0.615864,0.278892,0.082939,...,-0.291349,0.034514,0.041449,0.018437,0.038386,0.023341,0.156948,0.030552,-0.016988,0.045354
Name_Income_Type_Working,0.057481,0.136604,-0.024522,-0.056512,-0.043905,-5.737804e-02,0.304568,-0.483907,0.131320,0.007111,...,-0.166528,0.048702,-0.018636,0.020089,0.017997,0.003987,0.090151,0.002423,0.058383,0.020882
Days_Last_Phone_Change,0.055218,-0.005865,-0.018585,-0.073701,-0.063746,-7.628883e-02,0.082939,0.023032,-0.027109,1.000000,...,0.019629,0.019944,-0.031501,-0.014128,-0.009044,-0.002572,0.017307,-0.005469,0.004396,0.007806
Code_Gender_M,0.054713,0.047382,0.074730,0.021601,0.076993,2.250447e-02,0.148060,-0.156003,0.080543,0.025282,...,0.047794,0.088146,0.066783,-0.111712,-0.058734,-0.027030,-0.160078,-0.040910,0.111932,-0.030570
Occupation_Type_Drivers,0.030303,0.033313,0.019491,0.008390,0.034360,6.465147e-03,0.054303,-0.118105,0.051975,-0.005831,...,-0.250183,-0.021006,-0.069348,-0.042879,-0.023667,-0.012555,-0.086634,-0.016566,-0.037931,-0.016838
Occupation_Type_Low-skill Laborers,0.027591,0.004936,-0.012418,-0.028910,-0.022122,-3.133101e-02,0.034514,-0.038368,0.003843,0.019944,...,-0.081618,1.000000,-0.022624,-0.013989,-0.007721,-0.004096,-0.028263,-0.005404,-0.012374,-0.005493
Name_Family_Status_Single / not married,0.026518,-0.141051,-0.001542,-0.096918,-0.073171,-9.770930e-02,0.162267,-0.047744,-0.448216,0.061025,...,-0.016149,0.014566,-0.015682,-0.007173,0.012396,0.007058,0.020377,0.003545,0.001552,0.021887
Name_Family_Status_Civil marriage,0.022496,-0.015026,-0.001322,-0.046737,-0.044626,-5.045523e-02,0.065795,-0.050404,0.083143,0.011844,...,-0.021304,0.016898,-0.015103,0.001031,0.005378,0.001400,0.041923,0.001969,0.007162,0.010899
Occupation_Type_Sales staff,0.019537,0.040248,-0.023750,-0.030340,-0.023037,-3.127884e-02,0.156948,-0.158335,0.031709,0.017307,...,-0.336607,-0.028263,-0.093304,-0.057692,-0.031843,-0.016893,1.000000,-0.022288,-0.051034,-0.022654
Cnt_Children,0.019187,1.000000,0.012882,0.002145,0.021374,-1.826129e-03,0.330938,-0.239818,0.879160,-0.005865,...,-0.116228,0.004936,0.034996,0.019643,0.012564,0.006459,0.040248,0.009265,-0.008439,0.003259
Occupation_Type_Security staff,0.014648,-0.008439,-0.012063,-0.015578,-0.021068,-1.824238e-02,-0.016988,-0.069537,-0.003567,0.004396,...,-0.147378,-0.012374,-0.040852,-0.025259,-0.013942,-0.007396,-0.051034,-0.009759,1.000000,-0.009919
Occupation_Type_Cooking staff,0.012222,0.012990,-0.018003,-0.020881,-0.019623,-2.351152e-02,0.028673,-0.065567,0.011028,0.008355,...,-0.138442,-0.011624,-0.038375,-0.023728,-0.013097,-0.006948,-0.047940,-0.009167,-0.020990,-0.009317
Cnt_Fam_Members,0.009308,0.879160,0.016341,0.063160,0.075538,6.115335e-02,0.278892,-0.233549,1.000000,-0.027109,...,-0.114040,0.003843,0.044393,0.016621,0.004562,0.003715,0.031709,0.008502,-0.003567,-0.005124
Name_Income_Type_Unemployed,0.008784,-0.002755,-0.002078,0.003475,0.000624,5.176446e-03,-0.000314,0.018047,-0.003529,0.001823,...,0.008579,-0.000700,-0.002312,-0.001429,-0.000789,-0.000419,-0.002888,-0.000552,-0.001264,-0.000561
Occupation_Type_Waiters/barmen staff,0.007802,0.003259,-0.006863,-0.017735,-0.013056,-1.785007e-02,0.045354,-0.030852,-0.005124,0.007806,...,-0.065421,-0.005493,-0.018134,-0.011213,-0.006189,-0.003283,-0.022654,-0.004332,-0.009919,1.000000
Occupation_Type_Cleaning staff,0.006979,-0.009206,-0.019867,-0.027120,-0.035978,-2.980650e-02,-0.035244,-0.057720,-0.016069,0.008340,...,-0.122206,-0.010261,-0.033874,-0.020945,-0.011561,-0.006133,-0.042318,-0.008092,-0.018528,-0.008225
Name_Income_Type_Maternity leave,0.004726,0.005489,-0.000483,0.001510,0.002748,2.307337e-03,0.001122,-0.001897,0.005523,0.001154,...,-0.000749,-0.000334,-0.001102,-0.000681,-0.000376,-0.000200,-0.001377,-0.000263,-0.000603,-0.000268
Name_Family_Status_Separated,0.001168,-0.021851,0.002690,-0.030552,-0.038652,-3.224950e-02,-0.053140,0.007112,-0.229059,-0.007730,...,0.000532,-0.007024,-0.004898,0.009051,0.013694,0.000999,0.003519,-0.000795,0.001261,0.002677
Occupation_Type_Realty agents,-0.000394,0.006459,0.005468,0.006915,0.010652,6.543480e-03,0.023341,-0.022975,0.003715,-0.002572,...,-0.048783,-0.004096,-0.013522,-0.008361,-0.004615,1.000000,-0.016893,-0.003230,-0.007396,-0.003283
Name_Family_Status_Unknown,-0.000756,-0.001473,0.001693,0.000196,0.000773,-1.463165e-17,0.001997,-0.001165,-0.000428,0.000610,...,-0.002514,-0.000211,0.004317,-0.000431,-0.000238,-0.000126,-0.000871,-0.000166,-0.000381,-0.000169
Code_Gender_XNA,-0.001069,0.001663,0.000273,-0.001789,-0.001777,-1.138028e-03,0.002046,-0.001734,0.002366,0.000589,...,0.000051,0.010668,-0.000986,-0.000609,-0.000336,-0.000178,-0.001231,-0.000235,-0.000539,-0.000239
Name_Income_Type_Businessman,-0.001690,-0.002504,0.011633,0.008919,0.017929,1.065704e-02,-0.000046,-0.002692,-0.001582,0.001032,...,-0.003341,-0.000472,0.014139,-0.000964,-0.000532,-0.000282,-0.001947,-0.000372,-0.000852,-0.000378
Name_Income_Type_Student,-0.002267,0.001467,0.000055,-0.001677,-0.001014,-1.660532e-03,0.003031,-0.003591,0.001051,0.001971,...,0.000959,0.009706,-0.002091,-0.001293,-0.000714,-0.000379,-0.002612,-0.000499,-0.001144,0.005926
Occupation_Type_IT staff,-0.002445,-0.001130,0.007797,0.004995,0.005462,6.208639e-03,0.029925,-0.019312,-0.004606,0.004920,...,-0.040811,-0.003427,-0.011312,-0.006995,-0.003861,-0.002048,-0.014132,-0.002702,-0.006188,-0.002747
Occupation_Type_Secretaries,-0.002452,0.009265,-0.002273,-0.000893,-0.001149,-8.089199e-04,0.030552,-0.030693,0.008502,-0.005469,...,-0.064364,-0.005404,-0.017841,-0.011031,-0.006089,-0.003230,-0.022288,1.000000,-0.009759,-0.004332
Occupation_Type_HR staff,-0.002639,0.001391,0.003634,0.009146,0.009216,9.632879e-03,0.016538,-0.020036,0.000505,-0.004046,...,-0.042225,-0.003545,-0.011704,-0.007237,-0.003994,-0.002119,-0.014622,-0.002796,-0.006402,-0.002842
Occupation_Type_Laborers,-0.002880,-0.116228,-0.044101,-0.063806,-0.081396,-6.608745e-02,-0.291349,0.475069,-0.114040,0.019629,...,1.000000,-0.081618,-0.269445,-0.166603,-0.091957,-0.048783,-0.336607,-0.064364,-0.147378,-0.065421
Amt_Income_Total,-0.003982,0.012882,1.000000,0.156870,0.191657,1.596002e-01,0.027261,-0.064223,0.016341,-0.018585,...,-0.044101,-0.012418,0.105501,-0.013603,0.005325,0.005468,-0.023750,-0.002273,-0.012063,-0.006863
Occupation_Type_Private service staff,-0.005047,0.012564,0.005325,0.007332,0.013856,7.059215e-03,0.038386,-0.043608,0.004562,-0.009044,...,-0.091957,-0.007721,-0.025489,-0.015761,1.000000,-0.004615,-0.031843,-0.006089,-0.013942,-0.006189
Flag_Own_Realty2,-0.006148,-0.002366,0.002934,-0.039270,-0.005225,-4.552084e-02,-0.119146,0.069677,0.007350,0.027019,...,0.029888,-0.002905,-0.001900,0.001723,-0.001497,-0.002279,-0.005221,-0.004910,0.001391,-0.006949
Occupation_Type_Medicine staff,-0.008514,0.019643,-0.013603,0.003529,-0.014409,1.039541e-03,0.018437,-0.080815,0.016621,-0.014128,...,-0.166603,-0.013989,-0.046181,1.000000,-0.015761,-0.008361,-0.057692,-0.011031,-0.025259,-0.011213
Name_Income_Type_Commercial associate,-0.011906,0.028649,0.079371,0.097042,0.125704,9.660038e-02,0.166908,-0.257194,0.027158,-0.010577,...,-0.157600,-0.010990,0.119169,-0.044592,0.030900,0.023241,0.091279,0.004625,-0.000330,0.008392
Amt_Annuity,-0.012817,0.021374,0.191657,0.770127,1.000000,7.746605e-01,0.009445,-0.104331,0.075538,-0.063746,...,-0.081396,-0.022122,0.146186,-0.014409,0.013856,0.010652,-0.023037,-0.001149,-0.021068,-0.013056
Occupation_Type_High skill tech staff,-0.013766,0.015457,0.011610,0.021375,0.020837,2.301446e-02,0.057540,-0.092351,0.012573,-0.012059,...,-0.193275,-0.016228,-0.053574,-0.033126,-0.018284,-0.009700,-0.066928,-0.012798,-0.029303,-0.013008
Occupation_Type_Managers,-0.018648,0.034996,0.105501,0.119548,0.146186,1.268792e-01,0.041449,-0.128784,0.044393,-0.031501,...,-0.269445,-0.022624,1.000000,-0.046181,-0.025489,-0.013522,-0.093304,-0.017841,-0.040852,-0.018134
Name_Family_Status_Widow,-0.019394,-0.103722,-0.025561,-0.063239,-0.080432,-6.478144e-02,-0.267469,0.245702,-0.272036,0.003104,...,0.114627,-0.015187,-0.037678,-0.002812,-0.012753,-0.006595,-0.035511,-0.009497,-0.016643,-0.006306
Occupation_Type_Core staff,-0.020378,0.061285,0.005107,0.020426,0.009728,2.266269e-02,0.138577,-0.147971,0.054985,-0.001767,...,-0.309408,-0.025979,-0.085765,-0.053030,-0.029270,-0.015528,-0.107143,-0.020487,-0.046911,-0.020823
Occupation_Type_Accountants,-0.021610,0.017973,0.019739,0.049949,0.048531,5.413893e-02,0.051637,-0.085087,0.016068,-0.024357,...,-0.179003,-0.015030,-0.049618,-0.030680,-0.016934,-0.008983,-0.061985,-0.011853,-0.027139,-0.012047
Flag_Own_Car2,-0.021851,0.102023,0.083383,0.116225,0.141586,1.202823e-01,0.129879,-0.154441,0.149901,-0.039090,...,-0.074836,-0.005581,0.105531,-0.041552,-0.009500,-0.000476,-0.051502,-0.011176,0.016532,-0.019271
Name_Income_Type_State servant,-0.023447,0.047311,0.012714,0.048469,0.033381,4.772844e-02,0.060379,-0.131205,0.049980,-0.028181,...,-0.128069,-0.018951,0.031641,0.153216,-0.020484,-0.011319,-0.086357,0.033575,-0.008193,-0.008099
Name_Family_Status_Married,-0.025043,0.172702,0.012419,0.145288,0.138547,1.497443e-01,-0.009281,-0.051215,0.523014,-0.049871,...,-0.028347,-0.010537,0.040828,0.001349,-0.013548,-0.003528,-0.026195,0.000978,0.001517,-0.021323
Amt_Credit,-0.030369,0.002145,0.156870,1.000000,0.770127,9.865881e-01,-0.055436,-0.066838,0.063160,-0.073701,...,-0.063806,-0.028910,0.119548,0.003529,0.007332,0.006915,-0.030340,-0.000893,-0.015578,-0.017735
Amt_Goods_Price,-0.039628,-0.001826,0.159600,0.986588,0.774661,1.000000e+00,-0.053416,-0.064826,0.061153,-0.076289,...,-0.066087,-0.031331,0.126879,0.001040,0.007059,0.006543,-0.031279,-0.000809,-0.018242,-0.017850
Days_Employed,-0.044932,-0.239818,-0.064223,-0.066838,-0.104331,-6.482552e-02,-0.615864,1.000000,-0.233549,0.023032,...,0.475069,-0.038368,-0.128784,-0.080815,-0.043608,-0.022975,-0.158335,-0.030693,-0.069537,-0.030852
Name_Income_Type_Pensioner,-0.046209,-0.240719,-0.064018,-0.065753,-0.103720,-6.371940e-02,-0.620069,0.999534,-0.233974,0.021066,...,0.475192,-0.038790,-0.128056,-0.079128,-0.043703,-0.023185,-0.159948,-0.030590,-0.070043,-0.031092
Code_Gender_F,-0.054704,-0.047394,-0.074731,-0.021587,-0.076978,-2.249561e-02,-0.148074,0.156015,-0.080560,-0.025286,...,-0.047794,-0.088226,-0.066774,0.111715,0.058736,0.027031,0.160085,0.040911,-0.111927,0.030572

In [49]:
X = df2.drop(columns = ["Target"],axis = 1)
y = df2["Target"]

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [51]:
X_train

,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Days_Birth,Days_Employed,Cnt_Fam_Members,Days_Last_Phone_Change,Flag_Own_Car2,...,Occupation_Type_Laborers,Occupation_Type_Low-skill Laborers,Occupation_Type_Managers,Occupation_Type_Medicine staff,Occupation_Type_Private service staff,Occupation_Type_Realty agents,Occupation_Type_Sales staff,Occupation_Type_Secretaries,Occupation_Type_Security staff,Occupation_Type_Waiters/barmen staff
123473,0,171000.0,555273.0,16366.5,463500.0,-23349,365243,1.0,-2058.0,1,...,1,0,0,0,0,0,0,0,0,0
10118,1,157500.0,198085.5,23638.5,171000.0,-10921,-117,3.0,-73.0,0,...,1,0,0,0,0,0,0,0,0,0
64716,0,135000.0,776304.0,25173.0,648000.0,-23213,-2157,2.0,-1959.0,1,...,0,0,0,0,0,0,0,0,0,0
234940,1,164133.0,900000.0,36787.5,900000.0,-10703,-2530,3.0,-531.0,1,...,0,0,0,0,0,0,0,0,0,0
236051,0,225000.0,533668.5,21294.0,477000.0,-15798,-3520,2.0,-9.0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119879,0,121500.0,675000.0,32602.5,675000.0,-14481,-1124,1.0,-564.0,0,...,0,0,0,0,0,0,0,0,0,0
259178,2,225000.0,509922.0,40419.0,472500.0,-15492,-292,4.0,-1063.0,0,...,0,0,0,0,0,0,1,0,0,0
131932,0,450000.0,1125000.0,33025.5,1125000.0,-14309,-5929,1.0,-2267.0,1,...,0,0,1,0,0,0,0,0,0,0
146867,1,180000.0,270000.0,13500.0,270000.0,-12706,-1868,3.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
121958,0,157500.0,729792.0,35239.5,630000.0,-13176,-733,2.0,-862.0,1,...,1,0,0,0,0,0,0,0,0,0

In [52]:
X_test

,Cnt_Children,Amt_Income_Total,Amt_Credit,Amt_Annuity,Amt_Goods_Price,Days_Birth,Days_Employed,Cnt_Fam_Members,Days_Last_Phone_Change,Flag_Own_Car2,...,Occupation_Type_Laborers,Occupation_Type_Low-skill Laborers,Occupation_Type_Managers,Occupation_Type_Medicine staff,Occupation_Type_Private service staff,Occupation_Type_Realty agents,Occupation_Type_Sales staff,Occupation_Type_Secretaries,Occupation_Type_Security staff,Occupation_Type_Waiters/barmen staff
245895,2,207000.0,465457.5,52641.0,418500.0,-13297,-762,4.0,-2.0,1,...,0,0,0,0,0,0,1,0,0,0
98194,0,247500.0,1281712.5,48946.5,1179000.0,-14778,-1141,1.0,-1071.0,1,...,0,0,1,0,0,0,0,0,0,0
36463,0,202500.0,495000.0,39109.5,495000.0,-17907,-639,2.0,-1435.0,1,...,0,0,0,0,0,0,1,0,0,0
249923,0,247500.0,254700.0,24939.0,225000.0,-19626,-6982,1.0,-2000.0,0,...,0,0,0,0,0,0,0,0,0,0
158389,0,112500.0,308133.0,15862.5,234000.0,-20327,-1105,1.0,-173.0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256564,2,450000.0,900000.0,45000.0,900000.0,-18622,-2097,4.0,-1638.0,1,...,1,0,0,0,0,0,0,0,0,0
278889,0,225000.0,202500.0,24030.0,202500.0,-12325,-187,2.0,-1862.0,0,...,0,0,0,0,0,0,0,0,0,0
221828,0,121500.0,254700.0,30357.0,225000.0,-23629,365243,2.0,-1587.0,0,...,1,0,0,0,0,0,0,0,0,0
190245,1,112500.0,1314117.0,38551.5,1147500.0,-17350,-4118,3.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
253004,0,157500.0,521280.0,27423.0,450000.0,-18973,-3289,1.0,-572.0,0,...,1,0,0,0,0,0,0,0,0,0

In [53]:
y_train

123473    0
10118     0
64716     1
234940    0
236051    0
         ..
119879    0
259178    0
131932    0
146867    0
121958    1
Name: Target, Length: 246008, dtype: int64

In [54]:
y_test

245895    0
98194     0
36463     0
249923    0
158389    0
         ..
256564    0
278889    0
221828    0
190245    0
253004    0
Name: Target, Length: 61503, dtype: int64

In [55]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model

LogisticRegression(max_iter=1000)

In [56]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [57]:
y_pred = model.predict(X_test)

In [58]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(61503,))

In [59]:
y_test

245895    0
98194     0
36463     0
249923    0
158389    0
         ..
256564    0
278889    0
221828    0
190245    0
253004    0
Name: Target, Length: 61503, dtype: int64

In [60]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [61]:
accuracy_score(y_test,y_pred)

0.9195161211648212

In [62]:
confusion_matrix(y_test,y_pred)

array([[56553,     1],
       [ 4949,     0]])

In [63]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     56554
           1       0.00      0.00      0.00      4949

    accuracy                           0.92     61503
   macro avg       0.46      0.50      0.48     61503
weighted avg       0.85      0.92      0.88     61503

In [64]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [65]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [66]:
model.fit(X_train_scaled,y_train)

LogisticRegression(max_iter=1000)

In [67]:
y_pred2 = model.predict(X_test_scaled)

In [68]:
y_test

245895    0
98194     0
36463     0
249923    0
158389    0
         ..
256564    0
278889    0
221828    0
190245    0
253004    0
Name: Target, Length: 61503, dtype: int64

In [69]:
accuracy_score(y_test,y_pred2)

0.9195323805342829

In [70]:
confusion_matrix(y_test,y_pred2)

array([[56552,     2],
       [ 4947,     2]])

In [71]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     56554
           1       0.50      0.00      0.00      4949

    accuracy                           0.92     61503
   macro avg       0.71      0.50      0.48     61503
weighted avg       0.89      0.92      0.88     61503

In [ ]:
class FeatureClass:
    def __init__():
        pass

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("feat",FeatureClass())

    ("model", LogisticRegression(
        random_state=42,
        max_iter=1000
    ))
])

In [73]:
pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [74]:
pred = pipeline.predict(X_test)

In [75]:
sample = X_test.iloc[[0]]

prediction = pipeline.predict(sample)

probability = pipeline.predict_proba(sample)

print(prediction)
print(probability)

[0]
[[0.8663148 0.1336852]]

In [77]:
import joblib
joblib.dump(pipeline,"homecredit_model.pkl")

['homecredit_model.pkl']

In [78]:
feature_columns = X.columns.tolist()

joblib.dump(
    feature_columns,
    "feature_columns.pkl"
)

['feature_columns.pkl']